version: '3'

services:
  elasticsearch:
      build: elasticsearch/
      container_name: els-container
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - 9200:9200
        - 9300:9300
      environment:
        - cluster.name=elasticsearch
        - ES_JAVA_OPTS=-Xms256m -Xmx256m
        - XPACK_SECURITY_ENABLED=false
      networks:
        - elk
      healthcheck:
        test: curl http://elasticsearch:9200
        interval: 1s
        timeout: 3s
        retries: 60
  kibana:
    build: kibana/
    container_name: kib-container
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
  app:
    build: ./flask_app
    container_name: flk-container
    restart: always
    ports:
      - 5000:5000
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge
